// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdy6RKAKEzGDIHRXIl-VguMGzl5OtVE5k',
    appId: '1:971843975076:web:96bc40f8f926aae1133331',
    messagingSenderId: '971843975076',
    projectId: 'nba-trade-machine-c3583',
    authDomain: 'nba-trade-machine-c3583.firebaseapp.com',
    storageBucket: 'nba-trade-machine-c3583.appspot.com',
    measurementId: 'G-2PSC1K1NV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qamsVR9998sA7-TKsWxyvjFzcrmkVyM',
    appId: '1:971843975076:android:9e4d6b839b3221b2133331',
    messagingSenderId: '971843975076',
    projectId: 'nba-trade-machine-c3583',
    storageBucket: 'nba-trade-machine-c3583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEklKS7PR1wyeIObg5K6nqYl6HZ3utWg',
    appId: '1:971843975076:ios:9ff3623052b94522133331',
    messagingSenderId: '971843975076',
    projectId: 'nba-trade-machine-c3583',
    storageBucket: 'nba-trade-machine-c3583.appspot.com',
    iosBundleId: 'com.nba.nbatrade',
  );
}
